# -*- coding: utf-8 -*-
"""2020105643_이의준_PP05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WtFlu4zEsJtL00SjuXcTykv5k0-zy6v0

# **QueType.py**
"""

MAX_ITEMS = 100

class QueueType():
    def __init__(self):
        self.info = []
        self.maxQue = MAX_ITEMS + 1

    def enqueue(self, data):
        if self.is_full():
            return "Queue is full."
        else:
            self.info.append(data)

    def dequeue(self):
        if self.is_empty():
            return "Queue is empty."
        else:
            elem = self.info[0]
            self.info.remove(elem)
            return elem

    def is_empty(self):
        return len(self.info) == 0

    def is_full(self):
        return len(self.info) == self.maxQue

    def make_empty(self):
        self.info = []