version: '3.7'
services:
  manager:
    image: alpine:latest # https://hub.docker.com/_/alpine
    tty: true # https://docs.docker.com/engine/reference/run/
  worker1:
    image: nginx # https://hub.docker.com/_/nginx
    ports: # https://docs.docker.com/compose/compose-file/#ports
      - "8001:80"
  worker2:
    image: nginx
    ports:
      - "8002:80"